// Configure up to 50 questions here.
// Each question has:
// - text: the abstract or comment to show
// - isHuman: true if written by a human, false if generated by AI
// - type (optional): label such as "Thesis abstract", "Comment", etc.
const QUESTIONS = [
  {
    text: "En stor del av Sveriges bebyggelse har byggts mellan 1965 och 1974 eftersom det rådde stor bostadsbrist i Sverige. Regeringen beslutade att en miljon bostäder skulle uppföras under denna tid, det s.k. miljonprogrammet. Det byggdes bostäder i varierande former och storlekar för att bygga bort bostadsbristen. Storskaligheten och en stor grad av upprepning av identiska hus är kännetecken för miljonprogrammets bebyggelser. Nu är det dags att renovera dessa byggnader. I och med att dessa byggnader är av allmänt intresse då de speglar en del av Sveriges arkitekturhistoria ställer kommunerna vissa krav vid renovering av dem. Det kommunala företaget Gavlegårdarna i Gävle tar initiativ till att utveckla bygglovsprocessen för sådana bebyggelser. Detta görs för att reducera tiden för framställande av ett godkänt bygglov samt effektivisera och underlätta kommunikationen med kommunen under hela projektet. För att kunna bevara dessa byggnader i högsta möjliga mån har Gavlegårdarna utarbetat en effektiviseringsprocess genom att hyra in en extern bevarandeexpert för att fungera som en bro mellan företaget och kommunen samt för att kunna dela med sig av sina erfarenheter gällande bevarandet av det eventuella området. Dessutom har Gavlegårdarna låtit kommunen vara med från ett tidigt skede, d.v.s. redan från den första presentationen av förslaget. Därmed har kommunen fått vara med och medverka i förslaget, redan innan bygglovsansökan.",
    isHuman: true,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna uppsats undersöker Paulus förståelse av lagen, ett av de mest omstridda fälten inom paulusforskningen. Frågan om hur Paulus förhåller sig till lagen är så avgörande för helhetstolkningen av hans teologi att den som vill tolka Paulus och hans brev behöver ta ställning i ämnet. Litteraturen är omfattande och debatten tycks fortfarande vara långt ifrån avgjord. Samtidigt kräver en sådan problematik tydliga avgränsningar för att kunna hanteras inom ramen för en kortare studie. Därför avgränsas undersökningen till en specifik perikop i ett av Paulus brev där temat står i centrum. Uppsatsens huvudfråga formuleras så: Vad avser Paulus med uttrycket ”lagen” i Rom 3:21–31?",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "Denna studie behandlar teologiska tolkningar av två kungar som tillskrevs gudomlig status i det forntida Mesopotamien: den gammalakkadiske Naram-Sin (ca 2254–2218 f.Kr.) och den nysumeriske Shulgi (ca 2094–2047 f.Kr.). Perspektiven analyseras genom en induktivt orienterad historisk genomgång som tar sin utgångspunkt i tidigare forskning om ämnet. Eftersom arbetet är en c-uppsats och tillgången till primärmaterial (såsom arkeologiska fynd och källtexter på originalspråk) har varit begränsad, baseras undersökningen helt på sekundärlitteratur. Framställningen är uppdelad i tre avsnitt: två där respektive kung behandlas separat utifrån forskningsläget, och ett tredje där resultaten ställs mot varandra i en jämförande analys. Metoden har varit att först sammanställa vad forskare faktiskt hävdar om de teologiska föreställningarna kring monarkerna, därefter dela upp materialet i återkommande delteman och sortera utsagorna efter dessa. På grundval av detta försöker studien teckna en övergripande bild av perspektivens karaktär och deras huvudsakliga inriktningar. Tyngdpunkten ligger på att identifiera mönster i de religiösa idéerna och vilka motiv de främst kretsar kring. Resultatet visar att tolkningarna är mångfacetterade och delvis motstridiga, men att både skillnader och överlappningar kan urskiljas mellan kungarna. Två motiv som återkommer särskilt ofta är fruktbarhet och föreställningar kopplade till himlen.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
  {
    text: "In this comment, the author discusses the implications of large language models for academic writing and peer review processes.",
    isHuman: false,
    type: "Kandidatuppsats abstrakt",
  },
// Add up to 48 more questions here as needed.
];

// Thread-style Reddit-like discussions
// Each thread has a question and a list of comments
const THREADS = [
  {
    questionText: "Vad tycker ni om AI-genererade uppsatser i akademiska sammanhang?",
    comments: [
      {
        text: "Jag tycker det kan vara ett bra stöd, men studenten måste fortfarande stå för analysen.",
        isHuman: true,
      },
      {
        text: "Large language models enable unprecedented efficiency in knowledge production and assessment workflows.",
        isHuman: false,
      },
      {
        text: "Som handledare märker jag snabbt när en text inte låter som studenten själv.",
        isHuman: true,
      },
      {
        text: "It is empirically demonstrated that generative models always produce higher quality text than humans.",
        isHuman: false,
      },
    ],
  },
];

if (QUESTIONS.length === 0) {
  console.warn("QUESTIONS array is empty. Add at least one question in script.js.");
}

const MAX_QUESTIONS = 50;
if (QUESTIONS.length > MAX_QUESTIONS) {
  console.warn(`QUESTIONS has ${QUESTIONS.length} items, but only the first ${MAX_QUESTIONS} will be used.`);
}

const effectiveQuestions = QUESTIONS.slice(0, MAX_QUESTIONS);

// mode can be "intro", "reddit", "transition", "abstracts", "outro"
let mode = "intro";

let currentIndex = 0;
let hasAnsweredCurrent = false;
let numCorrect = 0;
let numAnswered = 0;

// State for reddit threads
let currentThreadIndex = 0;
let currentCommentIndex = 0;
let lastChoiceIsHuman = null;
let globalQuestionIndex = 0; // increments for every judgment (comment or abstract)
// Per-thread, per-comment answers: redditAnswers[threadIndex][commentIndex] = { choiceIsHuman }
let redditAnswers = [];
// When true, we're showing correct/incorrect for the current thread after user finished all comments
let redditShowingFeedback = false;


const RESULTS_ENDPOINT = "https://script.google.com/macros/s/AKfycbxAdn0Nk-FQVlgM8OyKfNw9HP7ugIv9xac50-duNwgcNLd6tlYN2VxY_NdwLiu0_gMb/exec";
const PARTICIPANT_ID = `${Date.now()}-${Math.floor(Math.random() * 1e6)}`;

const els = {
  questionLabel: document.getElementById("question-label"),
  questionTag: document.getElementById("question-tag"),
  questionText: document.getElementById("question-text"),
  commentsContainer: document.getElementById("comments-container"),
  controlsSection: document.querySelector(".controls"),
  subtitle: document.querySelector(".app-subtitle"),
  progressText: document.getElementById("progress-text"),
  progressBarInner: document.getElementById("progress-bar-inner"),
  btnHuman: document.getElementById("btn-human"),
  btnAi: document.getElementById("btn-ai"),
  btnPrev: document.getElementById("btn-prev"),
  btnExit: document.getElementById("btn-exit"),
  btnNext: document.getElementById("btn-next"),
  feedback: document.getElementById("feedback"),
  scoreCorrect: document.getElementById("score-correct"),
  scoreTotal: document.getElementById("score-total"),
};

const answers = new Array(effectiveQuestions.length).fill(null);

async function sendAnswerEvent() {
  let q;
  let choiceIsHuman;
  let extra = {};
  let questionType = "";

  if (mode === "abstracts") {
    q = effectiveQuestions[currentIndex];
    const answer = answers[currentIndex];
    if (!q || !answer) return;
    choiceIsHuman = answer.choiceIsHuman;

    const isCorrect = choiceIsHuman === q.isHuman;

    const totalAnswered = answers.filter(Boolean).length;
    const totalCorrect = answers.reduce((acc, a, idx) => {
      if (!a) return acc;
      return acc + (a.choiceIsHuman === effectiveQuestions[idx].isHuman ? 1 : 0);
    }, 0);

    extra = {
      mode: "abstracts",
      isCorrect,
      totalCorrectSoFar: totalCorrect,
      totalAnsweredSoFar: totalAnswered,
    };
    questionType = "abstract";
  } else if (mode === "reddit") {
    const thread = THREADS[currentThreadIndex];
    const comment = thread && thread.comments[currentCommentIndex];
    const stored = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex];
    if (!thread || !comment || !stored) return;
    q = { text: comment.text, isHuman: comment.isHuman };
    choiceIsHuman = stored.choiceIsHuman;

    const isCorrect = choiceIsHuman === q.isHuman;

    extra = {
      mode: "reddit",
      threadIndex: currentThreadIndex,
      commentIndex: currentCommentIndex,
      threadQuestionText: thread.questionText,
      isCorrect,
    };
    questionType = "comment";
  } else {
    return;
  }

  const payload = {
    participantId: PARTICIPANT_ID,
    response: {
      questionIndex: globalQuestionIndex,
      questionType,
      questionText: q.text,
      isHumanLabel: q.isHuman,
      userGuessIsHuman: choiceIsHuman,
      ...extra,
    },
  };

  try {
    await fetch(RESULTS_ENDPOINT, {
      method: "POST",
      // mode: "no-cors",   // this is optional now; you can keep or remove it
      body: JSON.stringify(payload),
    });
  } catch (err) {
    console.error("Failed to send answer event", err);
  }
}

function hideChoices(hide) {
  if (!els.controlsSection) return;
  if (hide) els.controlsSection.classList.add("controls--no-choices");
  else els.controlsSection.classList.remove("controls--no-choices");
}

function clampIndex(index) {
  if (index < 0) return 0;
  if (index >= effectiveQuestions.length) return effectiveQuestions.length - 1;
  return index;
}

function renderIntro() {
  hideChoices(true);

  if (els.subtitle) {
    els.subtitle.textContent = "Du kan svara på så många frågor du vill, och du kan avsluta när som helst.";
  }

  els.questionLabel.textContent = "Välkommen!";
  els.questionTag.textContent = "Information";
  els.questionText.textContent =
    "Tack för att du deltar.\n\n" +
    "Upplägg:\n" +
    "1) Först får du bedöma kommentarer i en forumtråd (likt Reddit).\n" +
    "2) Därefter får du bedöma abstrakt från kandidatuppsatser.\n\n" +
    "För varje text ska du avgöra om den är skriven av en människa eller av en AI.\n\n" +
    "Ingen identifierande information om dig sparas i resultatet (t.ex. namn, e-post eller IP-adress).\n\n" +
    "Du kan när som helst klicka på \"Avsluta\" för att gå direkt till avslutningssidan.";

  if (els.commentsContainer) els.commentsContainer.innerHTML = "";

  els.progressText.textContent = "";
  els.progressBarInner.style.width = "0%";

  els.btnPrev.disabled = true;
  els.btnNext.disabled = false;
  els.btnNext.textContent = "Starta ▶";
}

function renderQuestion() {
  hideChoices(false);
  const q = effectiveQuestions[currentIndex];
  const total = effectiveQuestions.length;
  const questionNumber = currentIndex + 1;

  els.questionLabel.textContent = `Fråga ${questionNumber}`;
  els.questionText.textContent = q.text;
  els.questionTag.textContent = q.type || "Item";

  els.progressText.textContent = `Fråga ${questionNumber} av ${total}`;
  const progressRatio = total > 0 ? questionNumber / total : 0;
  els.progressBarInner.style.width = `${Math.round(progressRatio * 100)}%`;

  els.btnPrev.disabled = currentIndex === 0;
  els.btnNext.disabled = !answers[currentIndex] && currentIndex !== total - 1;
  els.btnNext.textContent = currentIndex === total - 1 ? "Klara" : "Nästa ▶";

  resetChoiceStyles();
  applyAnswerStyles();
  renderFeedback();
  updateScoreSummary();
}

function renderThread() {
  const thread = THREADS[currentThreadIndex];
  if (!thread) return;
  hideChoices(false);

  if (!redditAnswers[currentThreadIndex]) {
    redditAnswers[currentThreadIndex] = thread.comments.map(() => null);
  }
  const threadAnswers = redditAnswers[currentThreadIndex];

  if (els.subtitle) {
    els.subtitle.textContent =
      "Läs kommentaren i tråden och avgör om den är skriven av en människa eller AI.";
  }

  els.questionLabel.textContent = `Tråd ${currentThreadIndex + 1}`;
  els.questionTag.textContent = "Kommentars-tråd";
  els.questionText.textContent = thread.questionText;

  if (els.commentsContainer) {
    els.commentsContainer.innerHTML = "";

    thread.comments.forEach((comment, idx) => {
      const row = document.createElement("div");
      let rowClass = "comment-row";
      if (redditShowingFeedback) {
        const ans = threadAnswers[idx];
        const isCorrect = ans && ans.choiceIsHuman === comment.isHuman;
        rowClass += isCorrect ? " comment-row--correct" : " comment-row--incorrect";
      } else if (idx === currentCommentIndex) {
        rowClass += " comment-row--active";
      }

      row.className = rowClass;

      const meta = document.createElement("div");
      meta.className = "comment-meta";
      meta.textContent = `Kommentar ${idx + 1}`;
      if (redditShowingFeedback && threadAnswers[idx]) {
        const ans = threadAnswers[idx];
        const isCorrect = ans.choiceIsHuman === comment.isHuman;
        const guess = ans.choiceIsHuman ? "Människa" : "AI";
        const actual = comment.isHuman ? "Människa" : "AI";
        meta.textContent += ` · Din bedömning: ${guess}. ${isCorrect ? "Rätt!" : "Rätt svar: " + actual + "."}`;
      }
      row.appendChild(meta);

      const body = document.createElement("div");
      body.className = "comment-body";
      body.textContent = comment.text;
      row.appendChild(body);
      els.commentsContainer.appendChild(row);
    });
  }

  const totalComments = thread.comments.length;
  const commentNumber = currentCommentIndex + 1;
  els.progressText.textContent = redditShowingFeedback
    ? `Resultat · Tråd ${currentThreadIndex + 1}`
    : `Kommentar ${commentNumber} av ${totalComments}`;
  const progressRatio = totalComments > 0 ? (redditShowingFeedback ? 1 : commentNumber / totalComments) : 0;
  els.progressBarInner.style.width = `${Math.round(progressRatio * 100)}%`;

  if (redditShowingFeedback) {
    els.btnPrev.disabled = true;
    els.btnNext.disabled = false;
    els.btnNext.textContent = currentThreadIndex === THREADS.length - 1 ? "Nästa del ▶" : "Nästa tråd ▶";
    resetChoiceStyles();
    els.feedback.textContent = "";
    els.feedback.classList.remove("correct", "incorrect");
    els.btnHuman.classList.add("disabled");
    els.btnAi.classList.add("disabled");
  } else {
    const currentAnswered = !!threadAnswers[currentCommentIndex];
    els.btnPrev.disabled = currentThreadIndex === 0 && currentCommentIndex === 0;
    els.btnNext.disabled = !currentAnswered;
    const isLastThread = currentThreadIndex === THREADS.length - 1;
    const isLastComment = commentNumber === totalComments;
    els.btnNext.textContent = isLastThread && isLastComment ? "Nästa del ▶" : "Nästa kommentar ▶";
    resetChoiceStyles();
    els.feedback.textContent = "";
    els.feedback.classList.remove("correct", "incorrect");
    if (currentAnswered) {
      const choice = threadAnswers[currentCommentIndex].choiceIsHuman;
      const btn = choice ? els.btnHuman : els.btnAi;
      btn.classList.add("selected", "disabled");
      (choice ? els.btnAi : els.btnHuman).classList.add("disabled");
    }
  }
}

function renderTransition() {
  if (els.subtitle) {
    els.subtitle.textContent =
      "Nu börjar nästa del: bedöm uppsatsabstrakt. Läs noggrant och avgör om texten är skriven av en människa eller AI.";
  }

  els.questionLabel.textContent = "Nästa del";
  els.questionTag.textContent = "Instruktion";
  els.questionText.textContent =
    "Du har nu bedömt kommentarer i en diskussionstråd. I nästa del får du läsa uppsatsabstrakt ett i taget och avgöra om de är skrivna av en människa eller av en AI.";

  if (els.commentsContainer) {
    els.commentsContainer.innerHTML = "";
  }

  els.progressText.textContent = "";
  els.progressBarInner.style.width = "0%";

  resetChoiceStyles();
  els.feedback.textContent = "";
  els.feedback.classList.remove("correct", "incorrect");

  hideChoices(true);
  els.btnPrev.disabled = true;
  els.btnNext.disabled = false;
  els.btnNext.textContent = "Starta abstrakt-delen ▶";
}

function renderOutro() {
  hideChoices(true);

  if (els.subtitle) {
    els.subtitle.textContent = "Tack för att du deltog!";
  }

  els.questionLabel.textContent = "Klart";
  els.questionTag.textContent = "Tack";
  els.questionText.textContent =
    "Tack för att du har genomfört undersökningen.\n\n" +
    "Du kan nu stänga sidan. Om du vill kan du också starta om och svara igen.";

  if (els.commentsContainer) els.commentsContainer.innerHTML = "";

  els.progressText.textContent = "";
  els.progressBarInner.style.width = "0%";

  els.btnPrev.disabled = true;
  els.btnNext.disabled = false;
  els.btnNext.textContent = "Starta om ▶";
}

function renderCurrent() {
  if (mode === "intro") {
    renderIntro();
  } else if (mode === "reddit") {
    renderThread();
  } else if (mode === "transition") {
    renderTransition();
  } else if (mode === "outro") {
    renderOutro();
  } else {
    renderQuestion();
  }
}

function resetChoiceStyles() {
  [els.btnHuman, els.btnAi].forEach((btn) => {
    btn.classList.remove("selected-correct", "selected-incorrect", "disabled");
  });
}

function applyAnswerStyles() {
  const q = effectiveQuestions[currentIndex];
  const answer = answers[currentIndex];

  if (!answer) return;

  const isCorrect = answer.choiceIsHuman === q.isHuman;
  const selectedButton = answer.choiceIsHuman ? els.btnHuman : els.btnAi;

  selectedButton.classList.add(isCorrect ? "selected-correct" : "selected-incorrect");
  [els.btnHuman, els.btnAi].forEach((btn) => btn.classList.add("disabled"));
}

function renderFeedback() {
  const q = effectiveQuestions[currentIndex];
  const answer = answers[currentIndex];

  els.feedback.textContent = "";
  els.feedback.classList.remove("correct", "incorrect");

  if (!answer) {
    return;
  }

  const isCorrect = answer.choiceIsHuman === q.isHuman;
  if (isCorrect) {
    els.feedback.textContent = 'Du har rätt!';
    els.feedback.classList.add("correct");
  } else {
    const actualLabel = q.isHuman ? "skrivet av en människa" : "skrivet av en AI";
    els.feedback.textContent = `Inte korrekt. Det var ${actualLabel}.`;
    els.feedback.classList.add("incorrect");
  }
}

function updateScoreSummary() {
  const totalAnswered = answers.filter(Boolean).length;
  const totalCorrect = answers.reduce((acc, a, idx) => {
    if (!a) return acc;
    return acc + (a.choiceIsHuman === effectiveQuestions[idx].isHuman ? 1 : 0);
  }, 0);

  numAnswered = totalAnswered;
  numCorrect = totalCorrect;

  els.scoreCorrect.textContent = numCorrect.toString();
  els.scoreTotal.textContent = numAnswered.toString();
}

function recordAnswer(choiceIsHuman) {
  if (mode === "abstracts") {
    const existing = answers[currentIndex];
    if (existing) {
      existing.choiceIsHuman = choiceIsHuman;
    } else {
      answers[currentIndex] = { choiceIsHuman };
    }
    hasAnsweredCurrent = true;
    globalQuestionIndex += 1;
    sendAnswerEvent();
    renderCurrent();
    return;
  }
  if (mode === "reddit" && !redditShowingFeedback) {
    if (!redditAnswers[currentThreadIndex]) {
      redditAnswers[currentThreadIndex] = THREADS[currentThreadIndex].comments.map(() => null);
    }
    redditAnswers[currentThreadIndex][currentCommentIndex] = { choiceIsHuman };
    lastChoiceIsHuman = choiceIsHuman;
    globalQuestionIndex += 1;
    sendAnswerEvent();
    renderThread();
  }
}

function handleNext() {
  if (mode === "intro") {
    mode = "reddit";
    currentThreadIndex = 0;
    currentCommentIndex = 0;
    redditShowingFeedback = false;
    renderThread();
    return;
  }
  if (mode === "reddit") {
    const thread = THREADS[currentThreadIndex];
    const totalComments = thread.comments.length;

    if (redditShowingFeedback) {
      redditShowingFeedback = false;
      if (currentThreadIndex < THREADS.length - 1) {
        currentThreadIndex += 1;
        currentCommentIndex = 0;
        renderThread();
        return;
      }
      mode = "transition";
      renderTransition();
      return;
    }

    if (currentCommentIndex < totalComments - 1) {
      currentCommentIndex += 1;
      lastChoiceIsHuman = (redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex])
        ? redditAnswers[currentThreadIndex][currentCommentIndex].choiceIsHuman
        : null;
      renderThread();
      return;
    }

    // On last comment: show feedback for this thread
    const lastAnswered = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][totalComments - 1];
    if (lastAnswered) {
      redditShowingFeedback = true;
      renderThread();
      return;
    }

    if (currentThreadIndex < THREADS.length - 1) {
      currentThreadIndex += 1;
      currentCommentIndex = 0;
      renderThread();
      return;
    }

    mode = "transition";
    renderTransition();
    return;
  }

  if (mode === "transition") {
    // Start abstracts part
    mode = "abstracts";
    currentIndex = 0;
    hasAnsweredCurrent = !!answers[currentIndex];
    if (els.subtitle) {
      els.subtitle.textContent =
        "Läs abstraktet och avgör om det är skrivet av en människa eller AI.";
    }
    renderQuestion();
    return;
  }

  if (mode === "outro") {
    // restart
    mode = "intro";
    currentIndex = 0;
    currentThreadIndex = 0;
    currentCommentIndex = 0;
    hasAnsweredCurrent = false;
    numCorrect = 0;
    numAnswered = 0;
    globalQuestionIndex = 0;
    redditAnswers = [];
    redditShowingFeedback = false;
    lastChoiceIsHuman = null;
    renderCurrent();
    return;
  }

  const lastIndex = effectiveQuestions.length - 1;

  if (currentIndex === lastIndex) {
    const percent =
      answers.length === 0
        ? 0
        : Math.round(
            (numCorrect / Math.max(1, answers.filter(Boolean).length)) * 100
          );

    mode = "outro";
    renderOutro();
    return;
  }

  currentIndex = clampIndex(currentIndex + 1);
  hasAnsweredCurrent = !!answers[currentIndex];
  renderQuestion();
}

function handlePrev() {
  if (mode === "reddit" && !redditShowingFeedback) {
    if (currentThreadIndex === 0 && currentCommentIndex === 0) return;

    if (currentCommentIndex > 0) {
      currentCommentIndex -= 1;
      const prevAns = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex];
      lastChoiceIsHuman = prevAns ? prevAns.choiceIsHuman : null;
      renderThread();
      return;
    }

    if (currentThreadIndex > 0) {
      currentThreadIndex -= 1;
      const thread = THREADS[currentThreadIndex];
      currentCommentIndex = thread.comments.length - 1;
      const prevAns = redditAnswers[currentThreadIndex] && redditAnswers[currentThreadIndex][currentCommentIndex];
      lastChoiceIsHuman = prevAns ? prevAns.choiceIsHuman : null;
      renderThread();
      return;
    }
  } else if (mode === "abstracts") {
    currentIndex = clampIndex(currentIndex - 1);
    hasAnsweredCurrent = !!answers[currentIndex];
    renderQuestion();
  }
}

function handleKeydown(event) {
  if (event.key === "ArrowLeft") {
    event.preventDefault();
    if (!els.btnPrev.disabled) handlePrev();
  } else if (event.key === "ArrowRight") {
    event.preventDefault();
    if (!els.btnNext.disabled) handleNext();
  } else if (event.key.toLowerCase() === "h") {
    event.preventDefault();
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(true);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(true);
    }
  } else if (event.key.toLowerCase() === "a") {
    event.preventDefault();
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(false);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(false);
    }
  }
}

function init() {
  if (els.btnExit) {
    els.btnExit.addEventListener("click", () => {
      mode = "outro";
      renderOutro();
    });
  }
  if (!els.btnHuman || !els.btnAi) {
    console.error("Required DOM elements not found. Check index.html structure.");
    return;
  }

  els.btnHuman.addEventListener("click", () => {
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(true);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(true);
    }
  });

  els.btnAi.addEventListener("click", () => {
    if (mode === "abstracts" && !answers[currentIndex]) {
      recordAnswer(false);
    } else if (mode === "reddit" && !redditShowingFeedback) {
      recordAnswer(false);
    }
  });

  els.btnNext.addEventListener("click", handleNext);
  els.btnPrev.addEventListener("click", handlePrev);

  document.addEventListener("keydown", handleKeydown);

  renderCurrent();
}

window.addEventListener("DOMContentLoaded", init);

